### ISSUE TITLE
Automatically Load Custom Preludes

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [CrystalSplitter/ghcitui#31]
A lot of my projects have a custom Prelude and it would be nice if this was automatically recognized and loaded instead of having to

1. specify the `-XNoImplicitPrelude` flag when starting the program
2. loading Prelude in the prompt
3. setting `-XImplicitPrelude`
4. loading the other modules

**Comment by BebeSparkelSparkel** [comment]
This is not a bug but a feature request.

**Comment by CrystalSplitter** [comment]
Can you describe your use case more? Isn't this something that your `cabal configuration` should be handling? I suppose I could add a flag to pass an `ImplicitPrelude` but that doesn't seem much different than passing `--cmd`?

What sort of ergonomics are you looking for here that's not covered by existing build systems?

**Comment by BebeSparkelSparkel** [comment]
Maybe I have been doing this incorrectly, but here is my use case where the Prelude is defined in the package not imported from a external package.

```text
$ ls -F . src
.:
app mypackage.cabal package.yaml stack.yaml src

src:
Prelude.hs Utils.hs Lib.hs Lib2.hs
```

mypackage.cabal

```cabal
cabal-version: 2.0
name: mypackage
version: 0.0.0.1
build-type: Simplef
library
  exposed-modules:
    Lib
    Lib2
  other-modules:
    Prelude
    Utils
  hs-source-dirs:
    src/
  build-depends:
      base
  mixins:
    base hiding (Prelude)
  default-language: Haskell2010
```

Utils.hs

```haskell
{-# LANGUAGE NoImplcitPrelude #-}
module Utils (func) where
...
```

Lib.hs

```haskell
module Lib (anotherFunc) where
import Utils (func)
...
```

Lib2.hs

```haskell
module Lib2 (anotherFunc2) where
...
```

For me to start a repl I need to run

```shell
$ stack repl --ghc-options -XNoImplicitPrelude
> :load Prelude
> :set -XImplicitPrelude
> :load Lib
> :load Lib2
```

which gets a bit tedious to type everytime I want the repl.
> :

**Comment by CrystalSplitter** [comment]
I'm sorry, I'm still somewhat missing the use case here.

There's a few things that stand out to me. The first is you probably shouldn't have a custom prelude module name `Prelude`, as this can break some bits of the [repl](https://github.com/haskell/containers/pull/922).

The second is why are you not using your Prelude as a mixin?

For example, consider this project layout

```shell
crystal@misty ~/t/cabal-pkg> tree
.
├── cabal-pkg.cabal
├── cabal.project
├── prelude
│   ├── mylude.cabal
│   └── MyLude.hs
└── src
    └──  Lib.hs

3 directories, 5 files
```

cabal-pkg.cabal

```cabal
cabal-version:      3.4
name:               cabal-pkg
version:            0.1.0.0
build-type:         Simple
library
    other-modules:    Lib
    build-depends:    base ^>=4.17.2.1, mylude
    hs-source-dirs:   src
    default-language: GHC2021
    mixins: base hiding (Prelude), mylude (MyLude as Prelude)
```

cabal.project

```yaml
packages: .
          prelude
```

mylude.cabal

```cabal
cabal-version:   3.4
name:            mylude
version:         0.1.0.0
build-type:      Simple
library
    exposed-modules:  MyLude
    build-depends:    base ^>=4.17.2.1
    hs-source-dirs:   .
    default-language: GHC2021
```

```hs
-- prelude/MyLude.hs
module MyLude (String, myFunc) where
import Prelude (String)
myFunc :: String -> String
myFunc x = x

-- src/Lib.hs
module Lib where
callingMyFunc :: String -> String
callingMyFunc = myFunc
```

This works just fine in cabal, and is quite clean. I have no idea if it works in stack, since I don't use stack. I can understand making a sub-package is a little weird, but it's the best option you have without [changes to cabal or GHC itself](https://discourse.haskell.org/t/a-modern-take-on-the-prelude/6619/19).

---

The third is: why aren't you using a .ghci file if you're rewriting the same commands over and over again at the start? Why not write a custom `--cmd` or symlink your own start up program for the repl?

Finally: I don't think any of the requests you've made are in the domain of ghcitui. These are all repl features which are in the domain of ghci, cabal, or stack. ghcitui is just an intermediary between these and a `brick` frontend.

Perhaps I'm deeply misunderstanding your feature request, but your request seems either already solved or requires things far beyond the scope of GHCiTUI.

**Comment by CrystalSplitter** [comment]
I'm going to close this one without a response; feel free to comment here asking for a reopen if you have more details about your use case!

**Comment by BebeSparkelSparkel** [comment]
Thanks for the good information and sorry for not looking into this more before posting the issue. I was ignorant of the features you pointed out and appreciate your suggestions.
